### PR TITLE
Add storageClass for variable declarations

### PR DESCRIPTION
**Pull request by vsilyaev**
This is part of facebook/infer#801, it adds optional storageClass to variableDeclarations, it's used to differentiate scope of global variables (file/static versus global), and it follows the precedent in function declarations.

### CODE REVIEW

**Comment by dulmarod** [comment]
`make -C libtooling test` is failing, @vsilyaev you need to re-record the tests.

**Comment by dulmarod** [comment]
For more info on tests, see https://github.com/facebook/facebook-clang-plugins/blob/master/CONTRIBUTING.md#pull-requests.

**Comment by vsilyaev** [comment]
@dulmarod , tests now updated. however I am not sure what to do with "(non-Darwin architecture detected)" tests , since if test results are affected, I will not be able to updated them.

**Comment by dulmarod** [comment]
Looks good now, we care mostly about the libtooling tests. They are passing now.

**Pull request merged**
