### PR TITLE
Detect CPU count on Linux and run make -j appropriately

### PR DESCRIPTION
**Pull request by stewart-ibm**
This massively speeds up building on machines with more than 8 CPU
threads (mine has 160).

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

(I can possibly get my employer to okay a CLA if it's available, I don't want to have to sign up for a work facebook account just to view it to get it to the appropriate people though)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Please get me a copy of the Corporate Contributor agreement that doesn't require me to have a facebook account just to read it to then pass it on to the legal ppl.

**Comment by matbd** [comment]
I don't think any Facebook account is required for this. Just click the link :)

**Comment by stewart-ibm** [comment]
For the individual one it isn't, for the Corporate one it is - https://developers.facebook.com/opensource/cla?type=company directs me to a login prompt.

**Comment by matbd** [comment]
Oh, indeed. Let me follow up internally on this.

**Comment by matbd** [comment]
Stewart did you receive my email with the CLA?

**Comment by stewart-ibm** [comment]
I did, thanks! Now I get to go check with legal (may take a little while due to my travel schedule)

**Comment by jvillard** [comment]
hi @stewart-ibm, any news? We'd like to merge this.

**Comment by jberdine** [comment]
Fixed in db9d0843c30ff7cdbc9600546b7fd8449d0ecf68.

**Pull request closed without merging**
